### PR TITLE
Nette 2.4 fix

### PR DESCRIPTION
**Pull request by Maxell92**

### CODE REVIEW

**Comment by h4kuna** [comment]
This PR is bad because abstract methods define my interface. There is idea remove this interface.

**Comment by h4kuna** [comment]
Fix in master, let's test it and confirm and I release new stable version.

**Comment by h4kuna** [comment]
Set stable version 4.2.2

**Comment by Maxell92** [comment]
I didn't realize that it's own interface. I tried master just now and it works 👍

**Pull request closed without merging**
