### PR TITLE
Update TExchange.php

### PR DESCRIPTION
**Pull request by djdaca**
Fix for Trait

### CODE REVIEW

**Comment by h4kuna** [comment]
Write use h4kuna\Exchange; and edit injectExchange(Exchange\Exchange $exchange) and annotation for property. You can remove phpdoc for injectExchange.

Maybe better is $exchange set as private and implement getter?

**Comment by djdaca** [comment]
mabe like protected

**Comment by h4kuna** [comment]
Ok protected.

**Comment by djdaca** [comment]
Ok, done

**Comment by h4kuna** [comment]
[Commited](../commit/03d78e8dd5efc88f04131b9b6ac1c609425e7791)

**Pull request closed without merging**
